spring:
  application:
    name: stock-seata
  datasource:
    druid:
      username: root
      password: root
      #mysql8以上
      url: jdbc:mysql://127.0.0.1:3306/nacos?serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=false&useUnicode=true
      #mysql8以上
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 5
      max-active: 20
      max-wait: 60000
      min-evictable-idle-time-millis: 30000
mybatis-plus:
  configuration:
    #驼峰命名
    map-underscore-to-camel-case: true