
spring:
  application:
    name: stock-seata-service
  datasource:
    druid:
      username: root
      password: root
      #mysql8以上
      url: jdbc:mysql://127.0.0.1:3306/nacos?serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=false&useUnicode=true
      #mysql8以上
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 5
      max-active: 20
      max-wait: 60000
      min-evictable-idle-time-millis: 30000
mybatis-plus:
  configuration:
    #驼峰命名
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
server:
  port: 6061
#告诉客户端怎么访问nacos上的seata服务的注册以及配置
seata:
  registry:
    type: nacos
    nacos:
      username: nacos
      password: nacos
      namespace: dev
      server-addr: 127.0.0.1:8847
      application: seata-server
  config:
    type: nacos
    nacos:
      username: nacos
      password: nacos
      namespace: dev
      server-addr: 127.0.0.1:8847
  tx-service-group: local

rocketmq:
  name-server: 127.0.0.1:9876
  consumer:
    group: consumer_1

