server:
  port: 8020
spring:
  application:
    name: order-service
  #服务名称，将被nacos识别
#nacos基本配置,注册中心服务密码账号
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        #username: nacos
        #password: nacos
        #namespace: nacos