
spring:
  application:
    name: order-seata-service
  datasource:
    druid:
      username: root
      password: root
      #mysql8以上
      url: jdbc:mysql://127.0.0.1:3306/nacos?serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=false&useUnicode=true
      #mysql8以上
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 5
      max-active: 20
      max-wait: 60000
      min-evictable-idle-time-millis: 30000
mybatis-plus:
  configuration:
    #驼峰命名
    map-underscore-to-camel-case: true
    #sql执行日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#  global-config:
      #设置全局表名前缀匹配实体类，例tableName=t_user,pojoName=user,不会出现找不到表的问题
      #或者使用@TableName在实体类上也可以
#      table-prefix: t_
      #数据库id主键自增
  mapper-locations: classpath:mapper/*.xml
#      id-type: auto
server:
  port: 6060
