server:
  port: 8021
spring:
  application:
    name: stock-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8847
        username: nacos
        password: nacos
        namespace: nacos